version: '3.8'

services:
  bot:
    build: .
    container_name: sport_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: sport_bot_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
